---
inventory: env_dev
limit: logical_broker_a
queueName: QUEUE_TO_CREATE_WITH_SUBS
queueSettings:
    accessType: non-exclusive
    eventMsgSpoolUsageThreshold:
        clearPercent: 30
        setPercent: 50
    ingressEnabled: true
    maxMsgSpoolUsage: 450
    maxTtl: 0
    owner: default
    permission: consume
    redeliveryEnabled: true
    rejectLowPriorityMsgEnabled: false
    rejectLowPriorityMsgLimit: 0
    respectMsgPriorityEnabled: false
    respectTtlEnabled: false
