- name: Multi-Queue Create or Update
  hosts: all
  gather_facts: false
  any_errors_fatal: true
  collections:
    - solace.pubsub_plus
  module_defaults:
    solace.pubsub_plus.solace_queue:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      timeout: "{{ sempv2_timeout }}"
      msg_vpn: "{{ msg_vpn }}"
    solace.pubsub_plus.solace_queue_subscriptions:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      timeout: "{{ sempv2_timeout }}"
      msg_vpn: "{{ msg_vpn }}"

  tasks:

    - name: Get secrets from file on disk
      ansible.builtin.include_vars:
        file: "{{ secrets_file }}"
      when: secrets_file is defined

    - name: create or update queues
      include_tasks: create-multi-queue-tasks.yaml
      loop: "{{ queueDefinitions }}"
      loop_control:
        loop_var: queueDefinition
