- name: Delete Solace Queue
  hosts: all
  gather_facts: false
  any_errors_fatal: true
  collections:
    - solace.pubsub_plus
  module_defaults:
    solace.pubsub_plus.solace_queue:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      timeout: "{{ sempv2_timeout }}"
      msg_vpn: "{{ msg_vpn }}"
    solace.pubsub_plus.solace_queue_subscription:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      timeout: "{{ sempv2_timeout }}"
      msg_vpn: "{{ msg_vpn }}"

  tasks:

    - name: Get secrets from file on disk
      ansible.builtin.include_vars:
        file: "{{ secrets_file }}"
      when: secrets_file is defined

    - name: delete solace queue
      solace_queue:
        name: "{{ queueName }}"
        username: "{{ broker_secrets[ inventory_hostname ].username }}"
        password: "{{ broker_secrets[ inventory_hostname ].password }}"
        state: absent

    # create user message
    - set_fact:
        broker_url: "{{ 'https' if sempv2_is_secure_connection else 'http' }}://{{ sempv2_host }}:{{ sempv2_port }}"

    - name: message
      debug:
        msg:
          - "playbook '{{ ansible_play_name }}' complete"
          - "broker: {{ broker_url }}"
          - "vpn:    {{ msg_vpn }}"
          - "queue:  {{ queueName }}"
